#for local testing
version: '3.8'

services:
  postgres:
    image: postgres:12.20
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - C:/Daten/postgres:/var/lib/postgresql/data
    networks:
      - container_network

  fddb-exporter:
    image: fddb-exporter
    container_name: fddb-exporter
    ports:
      - "8080:8080"
    environment:
      - FDDB-EXPORTER_FDDB_COOKIE=---
      - FDDB-EXPORTER_FDDB_BASICAUTH=---
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    depends_on:
      - postgres
    networks:
      - container_network

networks:
  container_network:
    driver: bridge
