// This TypeScript configuration file is generated by vaadin-maven-plugin.
declare module '*.css?inline' {
  import type {CSSResultGroup} from 'lit';
  const content: CSSResultGroup;
    export default content;
}

// Allow any CSS Custom Properties
declare module 'csstype' {
    interface Properties {
        [index: `--${string}`]: any;
    }
}
