apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "fddb-exporter.fullname" . } }
  labels:
    { { - include "fddb-exporter.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      { { - include "fddb-exporter.selectorLabels" . | nindent 6 } }
  strategy:
    type: Recreate
  template:
    metadata:
      { { - with .Values.podAnnotations } }
      annotations:
        { { - toYaml . | nindent 8 } }
      { { - end } }
      labels:
        { { - include "fddb-exporter.selectorLabels" . | nindent 8 } }
    spec:
      { { - with .Values.imagePullSecrets } }
      imagePullSecrets:
        { { - toYaml . | nindent 8 } }
      { { - end } }
      serviceAccountName: { { include "fddb-exporter.serviceAccountName" . } }
      securityContext:
        { { - toYaml .Values.podSecurityContext | nindent 8 } }
      containers:
        - name: { { .Chart.Name } }
          securityContext:
            { { - toYaml .Values.securityContext | nindent 12 } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          envFrom:
            - secretRef:
                name: { { .Values.fddb.auth.secretRef.name } }
            - configMapRef:
                name: { { include "fddb-exporter.fullname" . } }-config
          ports:
              - name: http
                containerPort: { { .Values.service.port } }
                protocol: TCP
          { { - if .Values.probes.liveness.enabled } }
          livenessProbe:
            httpGet:
              path: { { .Values.probes.liveness.path } }
              port: { { .Values.probes.liveness.port } }
            initialDelaySeconds: { { .Values.probes.liveness.initialDelaySeconds } }
            periodSeconds: { { .Values.probes.liveness.periodSeconds } }
            timeoutSeconds: { { .Values.probes.liveness.timeoutSeconds } }
            failureThreshold: { { .Values.probes.liveness.failureThreshold } }
            successThreshold: { { .Values.probes.liveness.successThreshold } }
          { { - end } }
          { { - if .Values.probes.readiness.enabled } }
          readinessProbe:
            httpGet:
              path: { { .Values.probes.readiness.path } }
              port: { { .Values.probes.readiness.port } }
            initialDelaySeconds: { { .Values.probes.readiness.initialDelaySeconds } }
            periodSeconds: { { .Values.probes.readiness.periodSeconds } }
            timeoutSeconds: { { .Values.probes.readiness.timeoutSeconds } }
            failureThreshold: { { .Values.probes.readiness.failureThreshold } }
            successThreshold: { { .Values.probes.readiness.successThreshold } }
          { { - end } }
          resources:
            { { - toYaml .Values.resources | nindent 12 } }
      { { - with .Values.nodeSelector } }
      nodeSelector:
        { { - toYaml . | nindent 8 } }
      { { - end } }
      { { - with .Values.affinity } }
      affinity:
        { { - toYaml . | nindent 8 } }
      { { - end } }
      { { - with .Values.tolerations } }
      tolerations:
        { { - toYaml . | nindent 8 } }
      { { - end } }