spring:
  application:
    name: fddbexporter
  datasource:
    url: jdbc:postgresql://postgres.misc:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

fddb-exporter:
  fddb:
    cookie: ---
    basicauth: ---

logger:
  levels:
    root: INFO