spring:
  application:
    name: fddbexporter
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fddb
      username: fddb
      password: password

fddb-exporter:
  fddb:
    cookie: ---
    basicauth: ---