spring:
  application:
    name: fddbexporter
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fddb
      username: user
      password: password
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: fddb-login-check,livenessState
        readiness:
          include: readinessState
          exclude: fddb-login-check
  health:
    defaults:
      enabled: true
    diskSpace:
      enabled: false
fddb-exporter:
  fddb:
    url: https://fddb.info
    username: ---
    password: ---
    min-days-back: 1
    max-days-back: 365
  scheduler:
    enabled: true
    cron: "0 0 3 * * *"

logging:
  level:
    root: INFO