spring:
  application:
    name: fddbexporter
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fddb
      username: user
      password: password

fddb-exporter:
  fddb:
    url: https://fddb.info
    cookie: ---
    basicauth: ---
  scheduler:
    enabled: true
    cron: "0 0 3 * * *"

logging:
  level:
    root: INFO