spring:
  application:
    name: fddb-exporter
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fddb
      username: mongodb_fddb_user
      password: mongodb_fddb_password
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, scheduledtasks
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: fddb-login-check,livenessState
        readiness:
          include: readinessState
          exclude: fddb-login-check
  health:
    defaults:
      enabled: true
    diskSpace:
      enabled: false

fddb-exporter:
  fddb:
    url: https://fddb.info
    username: ---
    password: ---
    min-days-back: 1
    max-days-back: 365
  scheduler:
    enabled: true
    cron: "0 0 3 * * *"
  telemetry:
    url: https://telemetry.itobey.dev
    username: fddb-exporter
    token: geXXjmYGbxfCxe3EX8onXH7yyg8ywxy9 #hard coded to prevent bots from accessing public endpoint
    cron: "0 0 4 * * *"
  persistence:
    mongodb:
      enabled: true
    influxdb:
      enabled: false
  influxdb:
    url: http://localhost:8086
    token: ---
    org: primary
    bucket: fddb-exporter

logging:
  level:
    root: INFO