{
 "title": "FDDB",
 "time": { "from": "2022-12-31T23:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "calories consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"fddb-exporter\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dailyTotals\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"calories\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "calories consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"fddb-exporter\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dailyTotals\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"calories\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Macros",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"fddb-exporter\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dailyTotals\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"calories\" or r[\"_field\"] == \"carbs\" or r[\"_field\"] == \"fat\" or r[\"_field\"] == \"protein\" or r[\"_field\"] == \"fibre\" or r[\"_field\"] == \"sugar\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Macros - Moving Averages (10d)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"fddb-exporter\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dailyTotals\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"calories\" or r[\"_field\"] == \"carbs\" or r[\"_field\"] == \"fat\" or r[\"_field\"] == \"protein\" or r[\"_field\"] == \"fibre\" or r[\"_field\"] == \"sugar\")\r\n  |> movingAverage(n: 10)  \r\n  |> yield(name: \"moving_average\")\r\n"
    }
   ]
  }
 ]
}